# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=500)),
                ('port', models.IntegerField()),
                ('ssl', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
