# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161028_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondb',
            name='project_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
