# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_connectiondb_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondb',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
