# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connectiondb_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiondb',
            old_name='project_name',
            new_name='name',
        ),
    ]
